version: '3.2'
services:
  db:
    container_name: db
    restart: unless-stopped
    image: postgres:latest
    environment:
      POSTGRES_USER: thingsflow
      POSTGRES_PASSWORD: rWuzPn3MfAULKkDp6Ttegb
      POSTGRES_DB: thingsflow
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "thingsflow", "-d", "thingsflow"]
      interval: 10s
      timeout: 3s
      retries: 3
  api:
    build:
      context: .
      dockerfile: Dockerfile  
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: thingsflow
      DB_PASSWORD: rWuzPn3MfAULKkDp6Ttegb
      DB_NAME: thingsflow
      JWT_ACCESS_TOKEN_SECRET: thingsflow
      JWT_ACCESS_TOKEN_EXPIRATION_TIME: 36500
      API_PORT: 9876
    ports:
      - 9876:9876
